In [18]:
import numpy as np

In [19]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [20]:
b = np.array([[5.0, 6.0, 7.0, 8.0],[4.0,3.0,1.0, 9.0]], dtype='int32')
print(b)
print(b[1][1])
print(b[1,1])
print(b[0])
print(b[:,1])
print(b[0][1:3])
print(b[0][1:4:2])
print(b[:,1:4:2])

[[5 6 7 8]
 [4 3 1 9]]
3
3
[5 6 7 8]
[6 3]
[6 7]
[6 8]
[[6 8]
 [3 9]]


In [21]:
print(b.ndim)
print(b.dtype)
print(b.shape)
print(b.itemsize)
print(b.size)
print(b.nbytes)

2
int32
(2, 4)
4
8
32


In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [25]:
np.full_like(b, 99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [26]:
np.random.rand(2,2)

array([[0.59763975, 0.2156841 ],
       [0.44003306, 0.05933363]])

In [27]:
np.random.randint(100, size=(3,5))

array([[68, 21, 51, 15, 54],
       [17, 91, 60, 59,  8],
       [ 4, 23, 54, 44, 72]])

In [28]:
np.random.randint(100,105, size=(3,5))

array([[100, 104, 100, 100, 101],
       [103, 104, 103, 104, 104],
       [104, 101, 101, 101, 100]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
sample = np.ones((5,5))
sample[1:4, 1:4] = np.zeros((3,3))
sample[2, 2] = 9
sample

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
c = np.array([2,3,4])
d = a.copy()
d[1] = 5
print(c)
print(d)

[2 3 4]
[1 5 3]


In [32]:
e = np.full((2,3), 4)
f = np.full((3,2), 3)
np.matmul(e, f)

array([[36, 36],
       [36, 36]])

In [33]:
g = np.array([[1, 2, 3], [4, 5, 6]])
np.max(g, axis=1)

array([3, 6])

In [55]:
np.sum(g, axis=0)

array([5, 7, 9])

In [35]:
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
h = np.array([1, 2, 3])
i = np.array([4, 5, 6])

np.vstack([h, i, h])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [37]:
np.hstack([i, h, i])

array([4, 5, 6, 1, 2, 3, 4, 5, 6])

In [38]:
filedata = np.genfromtxt('array.txt', delimiter=',')
filedata

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [39]:
filedata > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
~(filedata > 5)

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [41]:
filedata[filedata > 5]

array([ 6.,  7.,  8.,  9., 10., 11., 12.])

In [42]:
j = np.array([1, 2, 3, 4, 5])
j[[0, 2, 4]]

array([1, 3, 5])

In [43]:
np.any(filedata > 5, axis=0)

array([ True,  True,  True,  True])

In [44]:
np.all(filedata > 5, axis=0)

array([False, False, False, False])

In [45]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [46]:
np.random.permutation(np.arange(10))

array([9, 4, 5, 8, 7, 2, 3, 0, 6, 1])

In [47]:
import numpy.linalg as la

In [48]:
la.inv(np.random.rand(3,3))

array([[ 4.39903966, -1.68637597, -1.61361938],
       [ 1.35431232, -3.4367538 ,  1.89464924],
       [-1.5001121 ,  3.02726497, -0.25075843]])

In [49]:
k = np.array([[8,5,10],[3,9,4]])
m = k.copy()
m.sort(axis=0)
print(m)
k.sort(axis=1)
print(k)

[[ 3  5  4]
 [ 8  9 10]]
[[ 5  8 10]
 [ 3  4  9]]


In [50]:
n = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
n[::2, ::2]

array([[1, 3],
       [7, 9]])

In [51]:
np.where(n == 6)

(array([1], dtype=int64), array([2], dtype=int64))

In [53]:
o = np.random.rand(10000000)
%timeit np.sum(o)
%timeit sum(o)

16.6 ms ± 54.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.19 s ± 53.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
